### PR TITLE
Card number: CPW_2.0#30 / Carousel for Landing Pages by Role - fixing

### PR DESCRIPTION
**Pull request by joSecret**

### CODE REVIEW

**Comment by albertvolkman** [comment]
Thanks @joSecret! In the future, please assign tickets to me for review :)

**Comment by albertvolkman** [comment]
I see you're removing `_sass/partials/modules/_contractors-slider.scss`? If you are, you'd need to remove the reference to the partial, as it's currently erroring. However, removing it causes the slider to look like this-

Screen Shot 2020-10-22 at 10 59 59 AM

**Comment by joSecret** [comment]
I will look.

**Comment by joSecret** [comment]
Sorry. I make new pull request.

**Pull request closed without merging**
